calibs:
  0:
    sweeps:
    - curve: 0.06341552734375
      gibmag: 0.002010345458984375
      gibphase: 0.494384765625
      ogeemag: -0.330078125
      ogeephase: 0.255126953125
      phase: 0.0
      tilt: -0.050445556640625
    - curve: 0.294921875
      gibmag: 0.0016307830810546875
      gibphase: 2.353515625
      ogeemag: -0.31884765625
      ogeephase: 1.67578125
      phase: -0.005115509033203125
      tilt: 0.0413818359375
    uid: 3799407410
  1:
    sweeps:
    - curve: -0.01812744140625
      gibmag: 0.005657196044921875
      gibphase: 0.78955078125
      ogeemag: -0.60546875
      ogeephase: 1.076171875
      phase: 0.0
      tilt: -0.048370361328125
    - curve: 0.2366943359375
      gibmag: 0.00397491455078125
      gibphase: 2.134765625
      ogeemag: -0.55419921875
      ogeephase: 1.8720703125
      phase: -0.00554656982421875
      tilt: 0.046112060546875
    uid: 293199025
geos:
  0:
    origin:
    - -1.2479219436645508
    - 1.5177693367004395
    - 2.246342420578003
    rotation:
    - - 0.43372324109077454
      - 0.6762263774871826
      - 0.5954846739768982
    - - -0.4276021718978882
      - 0.7361947894096375
      - -0.5245699286460876
    - - -0.7931207418441772
      - -0.02711239829659462
      - 0.6084606647491455
  1:
    origin:
    - 1.3527175188064575
    - 1.5023266077041626
    - 2.3743395805358887
    rotation:
    - - -0.3472324013710022
      - 0.650687575340271
      - -0.6753038763999939
    - - -0.4270761013031006
      - -0.7508226037025452
      - -0.5038565397262573
    - - -0.8348866105079651
      - 0.11345081031322479
      - 0.5386030673980713
systemType: 2
type: lighthouse_system_configuration
version: '1'
